FROM node:16.16.0-slim

WORKDIR /frontend

COPY frontend/package*.json ./

RUN npm ci

COPY frontend/bundles-src/ bundles-src

RUN /frontend/node_modules/.bin/parcel build bundles-src/index.js --dist-dir bundles --public-url="./"
