# Generated by Django 3.2.15 on 2024-01-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_alter_order_designated_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('online', 'Электронно')], db_index=True, max_length=50, null=True, verbose_name='способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unprocessed', 'Необработанный'), ('prepare', 'Готовится'), ('is_delivered', 'Доставка'), ('done', 'Выполнен')], db_index=True, default='unprocessed', max_length=50, verbose_name='статус заказа'),
        ),
    ]
