# Generated by Django 3.2.15 on 2024-01-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_orderedproduct_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Необработанный'), (2, 'Готовится'), (3, 'Доставка'), (4, 'Выполнен')], db_index=True, default=1, verbose_name='статус заказа'),
        ),
    ]
