# Generated by Django 3.2.15 on 2024-01-12 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_auto_20240112_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='designated_restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodcartapp.restaurant', verbose_name='назваченный ресторан'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.IntegerField(choices=[(1, 'Наличные'), (2, 'Электронно')], db_index=True, null=True, verbose_name='способ оплаты'),
        ),
    ]
