# Generated by Django 3.2.15 on 2024-01-12 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_auto_20240112_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='designated_restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='foodcartapp.restaurant', verbose_name='назваченный ресторан'),
        ),
    ]
